[package]
name = "kv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
fs_extra = { git = "https://github.com/webdesus/fs_extra", version = "1.3.0" }
tempdir = "0.3.7"
